#!/bin/bash
LIBNAME=bcm2835

gcc -l$LIBNAME 2>&1 | grep -q "cannot find -l$LIBNAME"
if [ $? -eq 0 ] ; then
   echo "----------------------------------------------------------------------------"
   echo "Library BCM2835 not found!"
   echo "Make sure you follow instructions at http://www.airspayce.com/mikem/bcm2835/"
   echo "to install the BCM2835 library on your system."
   echo "----------------------------------------------------------------------------"
   exit 1
else
    echo "Library $LIBNAME found."
    node-gyp rebuild
fi
